### ISSUE TITLE
create a `git-metrics check` command

### ISSUE THREAD

**Issue by jdrouet** [jdrouet/git-metrics#45]
We should be able to set a budget for each metric.

Given the following example

```
- binary_size{plaftorm.os="linux"} 1000
+ binary_size{plaftorm.os="linux"} 1500 (+50.0%)
- binary_size{plaftorm.os="darwin"} 1000
+ binary_size{plaftorm.os="darwin"} 500 (-50.0%)
= binary_size{plaftorm.os="windows"} 1000
```

We should be able to set a absolute limit or a relative limit.

```toml
# should fail for the linux platform
[metrics.binary_size]
rules = [{ type = "max", value = 1200 }]

# should fail for the linux platform
# it's set to 10% and it increased by 50%
[metrics.binary_size]
rules = [{ type = "max-increase", value = 0.1 }]
```

TO CONTINUE
